FROM python:3.12-slim

# install UV
COPY --from=ghcr.io/astral-sh/uv:0.4.3 /uv /bin/uv

# copy files
COPY . /app/

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-dev --frozen

ENV PATH="/app/.venv/bin:$PATH"
CMD ["python", "hello.py"]