FROM python:3.12-slim

# install UV
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# copy files
COPY . /app/

WORKDIR /app
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen

CMD ["uv", "run", "hello.py"]