[project]
name = "uv-docker-examples"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.112.2",
    "pandas>=2.2.2",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.3",
]
